package Presentacion;

import Negocio.TareaValidaciones;
import Persistencia.Tarea;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSUE GOMEZ
 */
public class MenuPrincipal extends javax.swing.JFrame {
 private JPanel originalPanel;
    TareaValidaciones tVa = new TareaValidaciones();

    public MenuPrincipal() {
        initComponents();
        setupSpinner();
        DefaultTableModel modelo = crearModelo(tVa.obtenerTodasLasTareas());
        jTable1.setModel(modelo);
originalPanel = jPanel1; // Guarda la referencia del panel original
    }
    public JPanel getOriginalPanel() {

        return originalPanel;
    }

    private void setupSpinner() {
        // Crear y configurar el JLabel para la fecha
        JLabel lblFecha = new JLabel("Fecha:");

        // Crear y configurar el JSpinner para la fecha
        JSpinner spinnerFecha = new JSpinner(new SpinnerDateModel());
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(dateEditor);

        // Añadir JLabel y JSpinner al panel
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));  // Ajusta la posición según sea necesario
        jPanel1.add(spinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 120, 30)); // Ajusta la posición según sea necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ImagenMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        btnEliminar.setText("Eliminar tarea seleccionada");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 190, -1));

        btnAgregar.setText("Agregar tareas");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Titulo", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 750, -1));

        ImagenMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taskify_Principal.png"))); // NOI18N
        jPanel1.add(ImagenMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        PanelAgregarTarea panelAgregarTarea = new PanelAgregarTarea(tVa, this);
        cambiarPanel(panelAgregarTarea);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        tVa.eliminarTarea((String) jTable1.getValueAt(row, 0));
        actualizarTablaTareas();
        
    }//GEN-LAST:event_btnEliminarActionPerformed
    public static DefaultTableModel crearModelo(List<Tarea> listaTareas) {

        String[] columnas = {"Nombre", "Fecha"};

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Tarea tarea : listaTareas) {
            String nombre = tarea.getNombre();
            String fecha = sdf.format(tarea.getFecha());
            Object[] fila = {nombre, fecha};
            modelo.addRow(fila);
        }

        return modelo;
    }

    public void cambiarPanel(JPanel panel) {
        setContentPane(panel);
        invalidate();
        validate();
    }

    public void actualizarTablaTareas() {
        DefaultTableModel modelo = crearModelo(tVa.obtenerTodasLasTareas());
        jTable1.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenMenuPrincipal;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
